

CREATE TABLE ORGAO_PUBLICO ( 
   CNPJ         CHAR(14)      NOT NULL,
   RAZAO_SOCIAL VARCHAR(255),
   NOME         VARCHAR(100)  NOT NULL,
   RUA          VARCHAR(100),
   BAIRRO       VARCHAR(100),
   NUMERO       INTEGER,
   CEP          CHAR(8),

   CONSTRAINT PK_ORGAO_PUBLICO PRIMARY KEY (CNPJ)
);

CREATE TABLE EMPRESA_PUBLICA (
    CNPJ               CHAR(14)      NOT NULL,   
    RAZAO_SOCIAL       VARCHAR(100),
    NOME               VARCHAR(100)  NOT NULL,
    CNPJ_ORGAO_PUBLICO CHAR(14),

    CONSTRAINT PK_EMPRESA_PUBLICA PRIMARY KEY (CNPJ),

    CONSTRAINT FK_EMPRESA_ORGAO FOREIGN KEY (CNPJ_ORGAO_PUBLICO)
        REFERENCES ORGAO_PUBLICO (CNPJ)
        ON DELETE SET NULL
);

CREATE TABLE USUARIO (
    CPF  CHAR(11) NOT NULL,
    TIPO CHAR(1)  NOT NULL,  -- 'C' = Cidadão, 'G' = Gestor

    CONSTRAINT PK_USUARIO PRIMARY KEY (CPF),
    CONSTRAINT CK_USUARIO_TIPO CHECK (TIPO IN ('C','G'))
);

CREATE TABLE USUARIO_CIDADAO (
    CPF    CHAR(11)       NOT NULL,
    RUA    VARCHAR(100),
    BAIRRO VARCHAR(100),
    NUMERO INTEGER,
    CEP    CHAR(8),
    STATUS CHAR(1)        NOT NULL,      -- 'A' ou 'I'
    EMAIL  VARCHAR(100)   NOT NULL,
    SENHA  VARCHAR(100)   NOT NULL,

    CONSTRAINT PK_USUARIO_CIDADAO PRIMARY KEY (CPF),

    CONSTRAINT FK_CIDADAO_USUARIO
        FOREIGN KEY (CPF) REFERENCES USUARIO (CPF),

    CONSTRAINT CK_CIDADAO_STATUS CHECK (STATUS IN ('A','I'))
);

CREATE TABLE USUARIO_GESTOR (
    CPF                CHAR(11)       NOT NULL,
    RUA                VARCHAR(100),
    BAIRRO             VARCHAR(100),
    NUMERO             INTEGER,
    CEP                CHAR(8),
    CARGO              VARCHAR(100),
    EMAIL              VARCHAR(100)   NOT NULL,
    SENHA              VARCHAR(100)   NOT NULL,
    CNPJ_ORGAO_PUBLICO CHAR(14)       NOT NULL,

    CONSTRAINT PK_USUARIO_GESTOR PRIMARY KEY (CPF),

    CONSTRAINT FK_GESTOR_USUARIO
        FOREIGN KEY (CPF) REFERENCES USUARIO (CPF),

    CONSTRAINT FK_GESTOR_ORGAO
        FOREIGN KEY (CNPJ_ORGAO_PUBLICO) REFERENCES ORGAO_PUBLICO (CNPJ)
);


CREATE TABLE LINHA (
    NOME_CODIGO          VARCHAR(20)  NOT NULL,
    TARIFA               NUMERIC(6,2) NOT NULL,
    TEMPO_PERCURSO       INTEGER,
    ATIVO                CHAR(1)      NOT NULL,  -- 'S' ou 'N'
    CNPJ_EMPRESA_PUBLICA CHAR(14)     NOT NULL,

    CONSTRAINT PK_LINHA PRIMARY KEY (NOME_CODIGO),

    CONSTRAINT FK_LINHA_EMPRESA FOREIGN KEY (CNPJ_EMPRESA_PUBLICA)
        REFERENCES EMPRESA_PUBLICA (CNPJ),

    CONSTRAINT CK_LINHA_ATIVO CHECK (UPPER(ATIVO) IN ('S','N'))
);

CREATE TABLE PONTO_PARADA (
    NOME_CODIGO_LINHA   VARCHAR(20)  NOT NULL,
    NRO_PARADA          INTEGER      NOT NULL,
    RUA                 VARCHAR(100),
    BAIRRO              VARCHAR(100),
    NUMERO              INTEGER,
    CEP                 CHAR(8),
    PRESENCA_COBERTURA  CHAR(1),
    EH_ORIGEM           CHAR(1) DEFAULT 'N',
    EH_DESTINO          CHAR(1) DEFAULT 'N',

    CONSTRAINT PK_PONTO_PARADA
        PRIMARY KEY (NOME_CODIGO_LINHA, NRO_PARADA),

    CONSTRAINT FK_PONTO_LINHA
        FOREIGN KEY (NOME_CODIGO_LINHA)
        REFERENCES LINHA (NOME_CODIGO),

    CONSTRAINT CK_PONTO_COBERTURA
        CHECK (UPPER(PRESENCA_COBERTURA) IN ('S','N')),

    CONSTRAINT CK_PONTO_ORIGEM
        CHECK (UPPER(EH_ORIGEM) IN ('S','N')),

    CONSTRAINT CK_PONTO_DESTINO
        CHECK (UPPER(EH_DESTINO) IN ('S','N'))
);

CREATE TABLE ONIBUS (
    PLACA             VARCHAR(7)   NOT NULL,         
    NRO_PASSAGEIROS   INTEGER      NOT NULL,         
    ANO_FABRICACAO    INTEGER      NOT NULL,         
    ACESSIBILIDADE    CHAR(1),         
    NOME_CODIGO_LINHA VARCHAR(20)  NOT NULL,         
    HORARIO_INICIO    TIMESTAMP    NOT NULL,         
    HORARIO_FINAL     TIMESTAMP    NOT NULL,

    CONSTRAINT PK_ONIBUS
        PRIMARY KEY (PLACA),

    CONSTRAINT FK_ONIBUS_LINHA
        FOREIGN KEY (NOME_CODIGO_LINHA)
        REFERENCES LINHA (NOME_CODIGO),

    CONSTRAINT CK_ACESSIBILIDADE
        CHECK (UPPER(ACESSIBILIDADE) IN ('S','N')),

    CONSTRAINT CK_HORARIO
        CHECK (HORARIO_FINAL > HORARIO_INICIO)
);

CREATE TABLE VIAGEM (
    CPF_CIDADAO                    CHAR(11)      NOT NULL,
    PLACA_ONIBUS                   VARCHAR(7)    NOT NULL,
    DATAHORA_INICIO                TIMESTAMP     NOT NULL,
    DATAHORA_FINAL                 TIMESTAMP,
    CUSTO_TOTAL                    NUMERIC(8,2),
    NOME_CODIGO_LINHA_EMBARQUE     VARCHAR(20)   NOT NULL,
    NRO_PARADA_EMBARQUE            INTEGER       NOT NULL,
    NOME_CODIGO_LINHA_DESEMBARQUE  VARCHAR(20)   NOT NULL,
    NRO_PARADA_DESEMBARQUE         INTEGER       NOT NULL,

    CONSTRAINT PK_VIAGEM
        PRIMARY KEY (CPF_CIDADAO, DATAHORA_INICIO),

    CONSTRAINT FK_VIAGEM_CIDADAO
        FOREIGN KEY (CPF_CIDADAO)
        REFERENCES USUARIO_CIDADAO (CPF),

    CONSTRAINT FK_VIAGEM_ONIBUS
        FOREIGN KEY (PLACA_ONIBUS)
        REFERENCES ONIBUS (PLACA),

    CONSTRAINT FK_VIAGEM_PONTO_EMBARQUE
        FOREIGN KEY (NOME_CODIGO_LINHA_EMBARQUE, NRO_PARADA_EMBARQUE)
        REFERENCES PONTO_PARADA (NOME_CODIGO_LINHA, NRO_PARADA),

    CONSTRAINT FK_VIAGEM_PONTO_DESEMBARQUE
        FOREIGN KEY (NOME_CODIGO_LINHA_DESEMBARQUE, NRO_PARADA_DESEMBARQUE)
        REFERENCES PONTO_PARADA (NOME_CODIGO_LINHA, NRO_PARADA),

    CONSTRAINT CK_VIAGEM_DATAS
        CHECK (DATAHORA_FINAL IS NULL OR DATAHORA_FINAL > DATAHORA_INICIO),

    CONSTRAINT CK_VIAGEM_CUSTO
        CHECK (CUSTO_TOTAL IS NULL OR CUSTO_TOTAL >= 0)
);
